apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: brain-test-job
  namespace: dlrover
spec:
  distributionStrategy: ParameterServerStrategy
  optimizeMode: cluster
  resourceLimits:
    cpu: "1"
    memory: "10000Mi"
  replicaSpecs:
    ps:
      autoScale: True
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: registry.cn-hangzhou.aliyuncs.com/dlrover_deeprec/deeprec:v11
              imagePullPolicy: Always
              command:
                - /bin/bash
                - -c
                - "pip install pyhocon \
                  && cd /usr/local/lib/python3.8/dist-packages/\
                  dlrover/trainer/examples/deepfm_deeprec \
                  && python -m dlrover.trainer.entry.local_entry \
                  --platform=Kubernetes --conf=deepfm_deeprec_conf.TrainConf \
                  --enable_auto_scaling=True"
              volumeMounts:
                - name: pvc-nas
                  mountPath: /nas
          volumes:
            - name: pvc-nas
              persistentVolumeClaim:
                claimName: pvc-nas
    worker:
      autoScale: True
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: registry.cn-hangzhou.aliyuncs.com/dlrover_deeprec/deeprec:v11
              imagePullPolicy: Always
              command:
                - /bin/bash
                - -c
                - "pip install pyhocon \
                  && cd /usr/local/lib/python3.8/dist-packages/\
                  dlrover/trainer/examples/deepfm_deeprec \
                  && python -m dlrover.trainer.entry.local_entry \
                  --platform=Kubernetes --conf=deepfm_deeprec_conf.TrainConf \
                  --enable_auto_scaling=True"
              volumeMounts:
                - name: pvc-nas
                  mountPath: /nas
          volumes:
            - name: pvc-nas
              persistentVolumeClaim:
                claimName: pvc-nas
    dlrover-master:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              imagePullPolicy: Always
              # yamllint disable-line rule:line-length
              image: registry.cn-hangzhou.aliyuncs.com/dlrover/training-runtime:test
