apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: elasticjob-sample
  namespace: dlrover
spec:
  distributionStrategy: ParameterServerStrategy
  optimizeMode: cluster
  resourceLimits:
    cpu: "6"
    memory: "8192Mi"
  replicaSpecs:
    ps:
      restartCount: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: easydl/tf-estimator:iris_dnn_v0
              imagePullPolicy: IfNotPresent
              # yamllint disable
              command:
                - /bin/bash
                - -c
                - "python -m model_zoo.tf_estimator.iris_dnn_elastic"
              # yamllint enable
    worker:
      replicas: 0
      restartCount: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: easydl/tf-estimator:iris_dnn_v0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - "python -m model_zoo.tf_estimator.iris_dnn_elastic"
    dlrover-master:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              imagePullPolicy: Always
